# Generated by Django 2.0.7 on 2018-10-21 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_name', models.TextField(max_length=26)),
                ('description', models.CharField(max_length=280)),
                ('photo_url', models.URLField(default='https://gladstoneentertainment.com/wp-content/uploads/2018/05/avatar-placeholder.gif')),
                ('redirect_url', models.URLField(default='#')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
