# Generated by Django 2.0.7 on 2018-10-21 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(max_length=280),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='displayed_name',
            field=models.CharField(max_length=26),
        ),
    ]
