# Generated by Django 2.0.7 on 2018-10-21 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20181021_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='redirect_url',
            field=models.URLField(default='www.google.com'),
        ),
    ]
